title: Web Blog, weblog, etc.
author: Shepherd Professional
email: githubpages@shepherd.pro
description: > # this means to ignore newlines until "baseurl:"
  From weblogs to blogs to vlogs, the web has come a long way. We're here
  to help you or your small business get up and running online.
  Improve Google search results, improve customer interaction and much more.

# social links
twitter_username: @shepherd-professional
github_username:  shepherd-t

show_excerpts: false # set to false to remove excerpts on the homepage

theme: minima
